# Generated by Django 4.1.7 on 2023-04-02 11:52

import ckeditor.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=200)),
                ("platform", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=200)),
                ("college", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=200, null=True)),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(max_length=200)),
                ("Message", models.TextField()),
                ("phone", models.IntegerField(blank=True, null=True)),
                (
                    "interests",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATA SCIENCE", "DATA SCIENCE"),
                            ("DATA ANALYTICS", "DATA ANLYTICS"),
                            ("AGRICULTURAL ENGINEERNG", "AGRICULTURAL ENGINEERING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(blank=True, default=False, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["is_read", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("position", models.CharField(blank=True, max_length=200, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=500, null=True)),
                (
                    "short_intro",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="/uploads/profile/default_profileimage.jpg",
                        null=True,
                        upload_to=core.models.profile_image_file_path,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skillname", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATA SCIENCE", "DATA SCIENCE"),
                            ("DATA ANALYTICS", "DATA ANLYTICS"),
                            ("AGRICULTURAL ENGINEERNG", "AGRICULTURAL ENGINEERING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin", models.CharField(blank=True, max_length=2000, null=True)),
                ("github", models.CharField(blank=True, max_length=2000, null=True)),
                ("kaggle", models.CharField(blank=True, max_length=2000, null=True)),
                ("facebook", models.CharField(blank=True, max_length=2000, null=True)),
                ("instagram", models.CharField(blank=True, max_length=2000, null=True)),
                ("youtube", models.CharField(blank=True, max_length=2000, null=True)),
                ("website", models.CharField(blank=True, max_length=2000, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATA SCIENCE", "DATA SCIENCE"),
                            ("DATA ANALYTICS", "DATA ANLYTICS"),
                            ("AGRICULTURAL ENGINEERNG", "AGRICULTURAL ENGINEERING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        default="/uploads/project/default_thumbnail.jpg",
                        null=True,
                        upload_to=core.models.project_image_file_path,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLETED", "COMPLETED"),
                            ("ON GOING", "ON GOING"),
                            ("PENDING", "PENDING"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("demo_link", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "github_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "kaggle_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "other_source_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("project_date", models.DateField(blank=True, null=True)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("tags", models.ManyToManyField(to="core.tag")),
            ],
            options={
                "ordering": ["-project_date"],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATA SCIENCE", "DATA SCIENCE"),
                            ("DATA ANALYTICS", "DATA ANLYTICS"),
                            ("AGRICULTURAL ENGINEERNG", "AGRICULTURAL ENGINEERING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        default="/uploads/blog/default_thumbnail.jpg",
                        null=True,
                        upload_to=core.models.blog_image_file_path,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLETED", "COMPLETED"),
                            ("ON GOING", "ON GOING"),
                            ("PENDING", "PENDING"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("demo_link", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "github_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "kaggle_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "other_source_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("blog_date", models.DateField(blank=True, null=True)),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("tags", models.ManyToManyField(to="core.tag")),
            ],
            options={
                "ordering": ["-blog_date"],
            },
        ),
    ]
